source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Memelify' do
    pod 'Alamofire', '~> 4.7'
    pod 'surveymonkey-ios-sdk', '~> 2.0.0'
    pod 'Kingfisher', '~> 5.0'
    pod 'DZNEmptyDataSet'
end
