# Last Updated: November 2018
# Define required services in order for Memelify's backend to run.

version: '3'
services:
  memelify:  # Handle GET/POST requests from iOS clients.
    restart: always
    build: ./flask
    ports: 
      - "8000:8000"
    environment:
    command: gunicorn -w 1 -b :8000 autoapp:app --log-level=debug --log-file=-


  # nginx:   # web server
  #   restart: always
  #   build: ./nginx
  #   ports: 
  #     - "80:80"
  #   depends_on:
  #     - memelify